### PR TITLE
add initial tcp/tls connection support

### PR DESCRIPTION
**Pull request by andyli**
I briefly tested manually and it work for me.

I haven't write any test for tcp/tls yet since it most-likely need a mock server since it need to open a connection. I temporarily changed the test to using udp to avoid tcp connection error.

I suppose I will improve this a bit but I'm opening this PR now for your review.

### CODE REVIEW

**Comment by ovhemert** [comment]
Thanks for the addition, great work 👍🏻

Please continue to work on this, it would be nice to have TLS support.
(this is actually already on my list to have for some time)

I'd prefer the testing of the current udp, and now also the new tls, be done by stubbing the client libraries using `sinon` instead of spinning up a mock server. This would also make it possible to test on Windows again (currently disabled for that reason).

And maybe for now keep the current udp as the default so we can bump minor version? But I agree that with tls it would be more safe, and would like to make that the new default in future major version release.

**Comment by ovhemert** [comment]
Referring to issue #7 and #26

**Comment by anonrig** [comment]
👍 for this task. waiting for the merge :)

**Comment by andyli** [comment]
I've reverted the default connection to udp as suggested. Added tests of the tcp and tls connections with sinon, and the coverage is kept at 100%.

The style and how some things are done can be adjusted, but it would be more of a preference. I will leave it to you to tweak as you like :)

**Comment by andyli** [comment]
Done :)

**Comment by ovhemert** [comment]
Thanks for the additions, they will be in v1.3.x

**Pull request merged**
